rn <- c("Botterweg_Col-0_1.bam", "Botterweg_Col-0_2.bam", "Botterweg_rev5_1.bam", "Botterweg_rev5_2.bam", "Botterweg_wox4_1.bam", "Botterweg_wox4_2.bam", "Cai_Col-0_1.bam", "Cai_Col-0_2.bam", "Cai_Col-0_3.bam", "Cai_fio1_1.bam", "Cai_fio1_2.bam", "Cai_fio1_3.bam", "ParkerFpa_35SFPA8_1.bam", "ParkerFpa_35SFPA8_2.bam", "ParkerFpa_35SFPA8_3.bam", "ParkerFpa_35SFPA8_4.bam", "ParkerFpa_35SFPA8_5.bam", "ParkerFpa_35SFPA8_6.bam", "ParkerFpa_Col-0_1.bam", "ParkerFpa_Col-0_2.bam", "ParkerFpa_Col-0_3.bam", "ParkerFpa_Col-0_4.bam", "ParkerFpa_Col-0_5.bam", "ParkerFpa_Col-0_6.bam", "ParkerFpa_fpa8_1.bam", "ParkerFpa_fpa8_2.bam", "ParkerFpa_fpa8_3.bam", "ParkerFpa_fpa8_4.bam", "ParkerFpa_fpa8_5.bam", "ParkerFpa_fpa8_6.bam", "ParkerVir_Col-0_1.bam", "ParkerVir_Col-0_2.bam", "ParkerVir_Col-0_3.bam", "ParkerVir_Col-0_4.bam", "ParkerVir_Col-0_5.bam", "ParkerVir_Col-0_6.bam", "ParkerVir_VIRc_1.bam", "ParkerVir_VIRc_2.bam", "ParkerVir_VIRc_3.bam", "ParkerVir_VIRc_4.bam", "ParkerVir_VIRc_5.bam", "ParkerVir_VIRc_6.bam", "ParkerVir_vir1_1.bam", "ParkerVir_vir1_2.bam", "ParkerVir_vir1_3.bam", "ParkerVir_vir1_4.bam", "ParkerVir_vir1_5.bam", "ParkerVir_vir1_6.bam", "Parker_Col-0_04c_1.bam", "Parker_Col-0_04c_2.bam", "Parker_Col-0_04c_3.bam", "Parker_Col-0_04c_4.bam", "Parker_Col-0_04c_5.bam", "Parker_Col-0_04c_6.bam", "Parker_Col-0_12c_1.bam", "Parker_Col-0_12c_2.bam", "Parker_Col-0_12c_3.bam", "Parker_Col-0_12c_4.bam", "Parker_Col-0_12c_5.bam", "Parker_Col-0_12c_6.bam", "Parker_Col-0_20c_1.bam", "Parker_Col-0_20c_2.bam", "Parker_Col-0_20c_3.bam", "Parker_Col-0_20c_4.bam", "Parker_Col-0_20c_5.bam", "Parker_Col-0_20c_6.bam", "Parker_Col-0_28c_1.bam", "Parker_Col-0_28c_2.bam", "Parker_Col-0_28c_3.bam", "Parker_Col-0_28c_4.bam", "Parker_Col-0_28c_5.bam", "Parker_Col-0_28c_6.bam", "Parker_fio1_04c_1.bam", "Parker_fio1_04c_2.bam", "Parker_fio1_04c_3.bam", "Parker_fio1_04c_4.bam", "Parker_fio1_04c_5.bam", "Parker_fio1_04c_6.bam", "Parker_fio1_12c_1.bam", "Parker_fio1_12c_2.bam", "Parker_fio1_12c_3.bam", "Parker_fio1_12c_4.bam", "Parker_fio1_12c_5.bam", "Parker_fio1_12c_6.bam", "Parker_fio1_20c_1.bam", "Parker_fio1_20c_2.bam", "Parker_fio1_20c_3.bam", "Parker_fio1_20c_4.bam", "Parker_fio1_20c_5.bam", "Parker_fio1_20c_6.bam", "Parker_fio1_28c_1.bam", "Parker_fio1_28c_2.bam", "Parker_fio1_28c_3.bam", "Parker_fio1_28c_4.bam", "Parker_fio1_28c_5.bam", "Parker_fio1_28c_6.bam", "Sun_Col-0_1.bam", "Sun_Col-0_2.bam", "Sun_fio1-1_1.bam", "Sun_fio1-1_2.bam", "Sun_fio1-5_1.bam", "Sun_fio1-5_2.bam", "Wang_Col-0_1.bam", "Wang_Col-0_2.bam", "Wang_fio1_1.bam", "Wang_fio1_2.bam", "Wei_Col-0_1.bam", "Wei_Col-0_2.bam", "Wei_Col-0_3.bam", "Wei_Col-0_4.bam", "Wei_ect2_1.bam", "Wei_ect2_2.bam", "Wei_ect2_3.bam", "Wei_ect2_4.bam")
condition <- factor(c("Col-0", "Col-0", "rev5", "rev5", "wox4", "wox4", "Col-0", "Col-0", "Col-0", "fio1", "fio1", "fio1", "FPA8", "FPA8", "FPA8", "FPA8", "FPA8", "FPA8", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "fpa8", "fpa8", "fpa8", "fpa8", "fpa8", "fpa8", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "VIRc", "VIRc", "VIRc", "VIRc", "VIRc", "VIRc", "vir", "vir", "vir", "vir", "vir", "vir", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "Col-0", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "fio1", "Col-0", "Col-0", "fio1", "fio1", "fio1", "fio1", "Col-0", "Col-0", "fio1", "fio1", "Col-0", "Col-0", "Col-0", "Col-0", "ect2", "ect2", "ect2", "ect2"))
type <- factor(c("Botterweg", "Botterweg", "Botterweg", "Botterweg", "Botterweg", "Botterweg", "Cai", "Cai", "Cai", "Cai", "Cai", "Cai", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerFpa", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "ParkerVir", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Parker", "Sun", "Sun", "Sun", "Sun", "Sun", "Sun", "Wang", "Wang", "Wang", "Wang", "Wei", "Wei", "Wei", "Wei", "Wei", "Wei", "Wei", "Wei"))
samp <- data.frame(row.names=rn, condition, type)
dxd.fc <- DEXSeqDataSetFromFeatureCounts("/media/miyokawa/8TB-Data3/tech_data/count/dex_counts_all.txt",
                                         flattenedfile = "Araport11_GTF_genes_transposons.Apr2023_flat.gtf",
                                         sampleData = samp, design= ~ sample + exon + condition:exon)

dxd <- estimateSizeFactors(dxd.fc)

formulaFullModel    =  ~ sample + exon + type:exon + condition:exon
formulaReducedModel =  ~ sample + exon + type:exon 

multicoreParam <- MulticoreParam(workers = 8)
dxd = estimateDispersions( dxd, formula = formulaFullModel, BPPARAM=multicoreParam)

# Test for differential exon usage in each gene
dxd = testForDEU( dxd, reducedModel = formulaReducedModel, fullModel = formulaFullModel, BPPARAM=multicoreParam)

# Estimate relative exon usage fold changes
dxd <- estimateExonFoldChanges(dxd, fitExpToVar="condition", BPPARAM=multicoreParam)

dxr1 <- DEXSeqResults(dxd)
table <- as.data.frame(dxr1)
table$transcripts <- as.character(table$transcripts)
write.table(table, quote = F, sep = "\t", file = "DEXSeq_Parker_all.txt", row.names=F)
